name: "Run benchmark"
on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, edited]
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write
  pull-requests: write
  issues: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/federated-benchmark:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  benchmark:
    needs: build
    runs-on: ubuntu-latest
    # runs-on:
      # group: benchmark-runner
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        response:
          [
            big,
            medium,
            small
          ]
        service:
          [
            # the theoretical maximum
            # source_graphql,
            # source_rest_api,
            # nginx -> source: the baseline for comparison
            nginx_graphql,
            # nginx_rest_api,
            # tailcall configurations
            tailcall_default,
            # tailcall_tweaks,
            # tailcall_http_cache,
            # tailcall_cache_dir,
            # tailcall_dedupe_op,
            tailcall_full_conf,
            # wundergraph configurations
            wundergraph_no_opt,
            # wundergraph_dedupe,
            wundergraph_default,
            # apollo
            apollo_router,
            # grafbase
            grafbase_default,
            grafbase_cache
          ]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create "output.log" file
        run: touch ${{ github.workspace }}/output.log
      - id: benchmark
        name: Benchmark
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          image: ghcr.io/${{ github.repository_owner }}/federated-benchmark:latest
          options: -v ${{ github.workspace }}:/work
          run: ./docker_benchmark.sh ${{ matrix.response }} ${{ matrix.service }} >> /work/output.log
      - name: Print Result
        run: cat ${{ github.workspace }}/output.log
      - name: Extract Requests Per Second
        id: extract_rps
        run: |
          RPS=$(grep "Requests/sec:" ${{ github.workspace }}/output.log | awk '{print $2}')
          echo "${{ matrix.response }}_${{ matrix.service }}_rps=${RPS}" | tee -a "$GITHUB_OUTPUT"
  analyze:
    needs: benchmark
    runs-on: ubuntu-latest
    steps:
      - id: collect
        name: Collect Requests Per Second from all matrix jobs
        run: |
          echo "| Server | 112,838 bytes | 12598 bytes | 362 bytes |"
          echo "| --- | --- | --- | --- |"
          echo "| Nginx Default | ${{ needs.benchmark.extract_rps.big_nginx_graphql_rps }} | ${{ needs.benchmark.extract_rps.medium_nginx_graphql_rps }} | ${{ needs.benchmark.extract_rps.small_nginx_graphql_rps }} |"
          echo "| Base | --- | --- | --- |"
          echo "| Tailcall | ${{ needs.benchmark.extract_rps.big_tailcall_default_rps }} | ${{ needs.benchmark.extract_rps.medium_tailcall_default_rps }} | ${{ needs.benchmark.extract_rps.small_tailcall_default_rps }} |"
          echo "| Grafbase | ${{ needs.benchmark.extract_rps.big_grafbase_default_rps }} | ${{ needs.benchmark.extract_rps.medium_grafbase_default_rps }} | ${{ needs.benchmark.extract_rps.small_grafbase_default_rps }} |"
          echo "| Wundegraph | ${{ needs.benchmark.extract_rps.big_wundergraph_no_opt_rps }} | ${{ needs.benchmark.extract_rps.medium_wundergraph_no_opt_rps }} | ${{ needs.benchmark.extract_rps.small_wundergraph_no_opt_rps }} |"
          echo "| Apollo | ${{ needs.benchmark.extract_rps.big_apollo_router_rps }} | ${{ needs.benchmark.extract_rps.medium_apollo_router_rps }} | ${{ needs.benchmark.extract_rps.small_apollo_router_rps }} |"
          echo "| Cached | --- | --- | --- |"
          echo "| Tailcall | ${{ needs.benchmark.extract_rps.big_tailcall_full_conf_rps }} | ${{ needs.benchmark.extract_rps.medium_tailcall_full_conf_rps }} | ${{ needs.benchmark.extract_rps.small_tailcall_full_conf_rps }} |"
          echo "| Grafbase Cache | ${{ needs.benchmark.extract_rps.big_grafbase_cache_rps }} | ${{ needs.benchmark.extract_rps.medium_grafbase_cache_rps }} | ${{ needs.benchmark.extract_rps.small_grafbase_cache_rps }} |"
          echo "| Wundegraph Ludicrous | ${{ needs.benchmark.extract_rps.big_wundergraph_default_rps }} | ${{ needs.benchmark.extract_rps.medium_wundergraph_default_rps }} | ${{ needs.benchmark.extract_rps.small_wundergraph_default_rps }} |"
          | tee -a "$GITHUB_STEP_SUMMARY"